name: flutter_app_renamer
description: A command-line tool that makes it easy to change your Flutter AppName and BundleID.
version: 0.0.2
repository: https://github.com/MokuluaDev/flutter_app_renamer

environment:
  sdk: ^3.1.0

dependencies:
  rename: any
  yaml: any

dev_dependencies:
  lints: ^2.1.1

