name: flutter_app_renamer
description: A command-line tool that makes it easy to change your Flutter AppName and BundleID on all platforms.
version: 1.0.2
repository: https://github.com/MokuluaDev/flutter_app_renamer

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  rename: ^2.1.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1

executables:
  flutter_app_renamer:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://coindrop.to/mokulua